export const GET_AVAIL_SHIFTS_BEGIN = "GET_AVAIL_SHIFTS_BEGIN";
export const GET_AVAIL_SHIFTS_SUCCESS = "GET_AVAIL_SHIFTS_SUCCESS";
export const GET_AVAIL_SHIFTS_FAILURE = "GET_AVAIL_SHIFTS_FAILURE";
