export const GET_AVAIL_SHIFTS_BEGIN = "GET_AVAIL_SHIFTS_BEGIN";
export const GET_AVAIL_SHIFTS_SUCCESS = "GET_AVAIL_SHIFTS_SUCCESS";
export const GET_AVAIL_SHIFTS_FAILURE = "GET_AVAIL_SHIFTS_FAILURE";
export const BOOK_SHIFTS_BEGIN = "BOOK_SHIFTS_BEGIN";
export const BOOK_SHIFTS_SUCCESS = "BOOK_SHIFTS_SUCCESS";
export const BOOK_SHIFTS_FAILURE = "BOOK_SHIFTS_FAILURE";
